### PR TITLE
load global stylesheet with config initializer

### PR DESCRIPTION
**Pull request by jgnatch**
Hey @kitop, 

This is still WIP. Tests need to be added.

I didn't manage to set it up via application.rb so I went with an initializer. Feel free to change it if it's easy to do it the other way.

One cool and unplanned feature is that anyone can load a stylesheet and overwrite MountainView's styles and customize it to fit their look & feel :smiley:

### CODE REVIEW

**Comment by kitop** [comment]
Looks really good!!! 
The configuration file looks good, we can try to move it to Rails config later, if it seems worth it.

+ 1 to tests and hound comments.

We can also use this configuration object for styleguide specific stylesheets in the future :)

**Comment by jgnatch** [comment]
@kitop Thanks for the comments.

I've added a couple of tests. Let me know if they look good.

Cheers!

**Comment by kitop** [comment]
Looks good!! :+1: 

Only one thing: what do you think of testing `MountainView.configure` instead of directly the configuration class? Would it make sense?
Something like
```ruby
MountainView.configure do |config|
  config.included_stylesheets << "foo"
end

assert_equal ["foo"], MountainView.configuration.included_stylesheets
```

**Comment by jgnatch** [comment]
@kitop 

If test directly MountainView.configure and do it like you say, I get this Error:

 5) Error:
MountainViewTest#test_shows_styleguide:
ActionView::Template::Error: couldn't find file 'foo'

It seems that file `foo.css` should be present in the dummy app. I would leave this test like it is as we also test it this the dummy app in the integration test:

```
  test "global stylesheets are properly served" do
    get "/assets/mountain_view.css"

    assert_response :success
    assert_match(/Global Stylesheet Beginning/, response.body)
  end
```

What do you say?

**Comment by kitop** [comment]
Agh, right, because it actually configures MountainView for the demo app :/

Yeah, leaving it as is seems good then! 

:shipit:

**Pull request merged**
