### PR TITLE
Fix link to rizzo

### PR DESCRIPTION
**Pull request by Fodoj**

### CODE REVIEW

**Comment by kitop** [comment]
@Fodoj thanks!

**Comment by jgnatch** [comment]
@Fodoj thanks man! Are you using MountainView? any feedback :grin:

**Comment by Fodoj** [comment]
@jgnatch I am thinking about using it for one of my projects. I like the idea _a lot_, but so far I don't like that I can't use URL's inside components without prefixing them with `main_app`. Also, keeping assets in components folder instead of assets folder feels a bit weird. I will tell you more once I will start really using it :)

**Comment by Fodoj** [comment]
But your gem is really new, right? Never heard about it before and found by accident while investigating different solutions for living styleguide

**Comment by jgnatch** [comment]
@Fodoj yep! it is quite new. 

Regarding the paths prefix. We are opening an enhancement issue now about it and we will try to change this during these days. Probably we will have to remove the isolate_namespace part.

Of course, if you have any ideas, feel free to send a PR.

Cheers!

Nacho

**Pull request merged**
